{% set name = "pycoare" %}
{% set version = "2023.10b1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/pycoare-{{ version }}.tar.gz
  sha256: 1a83888c97a7b82f20e2c7842444198aa45336e3174f45f3dd4aac6f7fb3b8bf

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python >=3.7
    - setuptools
    - pip
  run:
    - python >=3.7
    - numpy

test:
  imports:
    - pycoare
  commands:
    - pip check
  requires:
    - pip

about:
  summary: A Python implementation of the COARE bulk air-sea flux algorithm
  home: https://pypi.org/project/pycoare
  dev_url: https://github.com/pyCOARE/coare
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - ocefpaf
